contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #trimmomatic channel"
    url: https://nfcore.slack.com/channels/trimmomatic
    about: Discussion about the nf-core/trimmomatic pipeline
